baseURL = "https://game.dndc.dev/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "dndc.dev別館 ～ゲーム保管庫～"
theme = "nagoya"
hasCJKLanguage = true
paginate = 7
canonifyurls = true

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  search = "search"

# ------
# Markup
# ------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
  author = "Dondoco"
  authorLink = false
  description = "黒い砂漠をメインにゲームを遊んでいます。Steamゲーも色々！"
  keywords = ["黒い砂漠", "MMO", "PCゲー", "Steam"]
  showAuthor = false
  showLastmod = true
  showSummary = true
  tersePagination = true
  paginationSlots = false
  showTreeCount = true
  sidebarSearch = true
  newNum = 5
  newText = "最新記事"
  readNextText = "関連記事"
  relatedNum = 5
  randomNum = 5
  shuffleSeeAlso = false
  showHeaderText = true
  toc = false