# Tranquilpeak
# Version : 0.5.3-BETA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseURL = "https://game.dndc.dev/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "dndc.dev別館 ～ゲーム保管庫～"
theme = "nagoya"
hasCJKLanguage = true
# googleAnalytics = "UA-123-45"
paginate = 7
canonifyurls = true

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  search = "search"

# ------
# Markup
# ------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
  author = "Dondoco"
  showAuthor = false
